### ISSUE TITLE
SSL via Lets Encrypt

### ISSUE THREAD

**Issue by cvburgess** [sparkthecause/daily-api#48]
## Description
- TLS/SSL stopped working and the site in general isn't loading(?)
- Need to implement a temporary solution
- Need to possibly "upgrade" to a Let's Encrypt solution
## Tasks
- [ ] Generate SSL certificate (if needed)
- [ ] Force SSL for all API requests
- [ ] Update DNS (if needed)
## Links and Resources

CloudFlare free blanket SSL
- https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku

Let's Encrypt Express:
- https://github.com/Daplie/letsencrypt-express
- http://justinmccandless.com/post/setting-up-https-on-node-for-free-with-lets-encrypt/

Heroku SSL Beta:
- https://devcenter.heroku.com/articles/ssl-beta
