### ISSUE TITLE
Configure DB for Heroku review apps

### ISSUE THREAD

**Issue by cvburgess** [sparkthecause/daily-api#54]
## Description
- Issue: The DB name is dynamic.
- Solution: Use a `postdeploy` script to configure database for a Heroku review app (or any other env)
## Tasks
- [x] Update schema.sql
- [x] Update data.sql
- [x] Create dynamic `postdeploy` script
- [x] Update Heroku / Codeship to use new `postdeploy` script
## Helpful links:
- https://devcenter.heroku.com/articles/github-integration-review-apps
