### ISSUE TITLE
Migrate templates to a local folder

### ISSUE THREAD

**Issue by cvburgess** [sparkthecause/daily-api#55]
## Description

Right now templates and blurbs are hosted on the CDN which is great... but slows down the dev process and is unnecessary HTTP calls.
## Tasks
- [x] Download and save templates
- [x] Reconfigure email helper to use local files
- [x] MAYBE: Migrate templates to a separate package
- [x] MAYBE: Make templates "dumber" and move any logic to wrapper functions
